services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    ports:
      - "1242:1242"
    volumes:
      - ${CONTAINER_ROOT}/ASF/config:/app/config
      - ${CONTAINER_ROOT}/ASF/plugins:/app/plugins
      - ${CONTAINER_ROOT}/ASF/logs:/app/logs
    env_file:
      - ../_shared/common.env
      - .env
    restart: unless-stopped